sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t  angelobms/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true angelobms/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-439668256204"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_ai: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

